[build-system]
requires = ["setuptools", "cython"]
build-backend = "setuptools.build_meta"

[tool.mypy]
mypy_path = ["$MYPY_CONFIG_FILE_DIR/src"]
packages = ["pyfuse3"]
modules = ["_pyfuse3", "pyfuse3_asyncio"]
namespace_packages = false
strict = true

[tool.cibuildwheel]
build = "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"

skip = "*-win32 *-manylinux_i686 *-musllinux*"

before-all = [
    # Linux
    "bash -c 'if command -v yum >/dev/null 2>&1; then yum update -y && yum install -y fuse3-devel pkgconfig; elif command -v apt-get >/dev/null 2>&1; then apt-get update && apt-get install -y libfuse3-dev pkg-config; fi'",
    # macOS
    "bash -c 'if [[ \"$OSTYPE\" == \"darwin\"* ]]; then brew install macfuse pkg-config || true; fi'"
]

before-build = [
    "pip install setuptools cython",
    "python setup.py build_cython"
]

test-requires = ["pytest", "pytest-trio", "trio"]
test-command = "python -c \"import pyfuse3; print('pyfuse3 imported successfully')\""

[tool.cibuildwheel.linux]
environment = { PKG_CONFIG_PATH = "/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/lib/pkgconfig:/usr/share/pkgconfig" }

[tool.cibuildwheel.macos]
environment = { PKG_CONFIG_PATH = "/usr/local/lib/pkgconfig:/opt/homebrew/lib/pkgconfig" }